---
title: "Irregular Verbs"
output:
  pdf_document

---
| Forma Original | Presente Afirmativo | Participio Presente | Pasado Afirmativo | Pasado Participio | Traducción |
|---|---|---|---|---|---|
| arise | arises | arising | arose | arisen | surgir |
| awake | awakes | awaking | awoke | awoken | despertar |
| backslide | backslides | backsliding | backslid | backslid | recaer |
| be | am/is/are | being | was/were | been | ser, estar |
| bear | bears | bearing | bore | borne | soportar |
| beat | beats | beating | beat | beaten | golpear |
| become | becomes | becoming | became | become | convertirse |
| befall | befalls | befalling | befell | befallen | suceder |
| beget | begets | begetting | begot | begotten | engendrar |
| begin | begins | beginning | began | begun | empezar |
| behold | beholds | beholding | beheld | beheld | contemplar |
| bend | bends | bending | bent | bent | doblar |
| beseech | beseeches | beseeching | beseeched | beseeched | suplicar |
| bet | bets | betting | bet | bet | apostar |
| bid | bids | bidding | bid | bid | pujar |
| bind | binds | binding | bound | bound | atar |
| bite | bites | biting | bit | bitten | morder |
| bleed | bleeds | bleeding | bled | bled | sangrar |
| blow | blows | blowing | blew | blown | soplar |
| break | breaks | breaking | broke | broken | romper |
| breed | breeds | breeding | bred | bred | criar |
| bring | brings | bringing | brought | brought | traer |
| broadcast | broadcasts | broadcasting | broadcast | broadcast | transmitir |
| browbeat | browbeats | browbeating | browbeat | browbeaten | intimidar |
| build | builds | building | built | built | construir |
| burn | burns | burning | burned | burned | quemar |
| burst | bursts | bursting | burst | burst | estallar |
| bust | busts | busting | busted | busted | romper |
| buy | buys | buying | bought | bought | comprar |
| cast | casts | casting | cast | cast | lanzar |
| catch | catches | catching | caught | caught | atrapar |
| chide | chides | chiding | chided | chided | regañar |
| choose | chooses | choosing | chose | chosen | elegir |
| cling | clings | clinging | clung | clung | aferrarse |
| clothe | clothes | clothing | clothed | clothed | vestir |
| come | comes | coming | came | come | venir |
| cost | costs | costing | cost | cost | costar |
| cut | cuts | cutting | cut | cut | cortar |
| dare | dares | daring | durst | dared | atreverse |
| deal | deals | dealing | dealt | dealt | tratar |
| dig | digs | digging | dug | dug | cavar |
| dive | dives | diving | dove | dived | bucear |
| do | does | doing | did | done | hacer |
| draw | draws | drawing | drew | drawn | dibujar |
| dream | dreams | dreaming | dreamed | dreamed | soñar |
| drink | drinks | drinking | drank | drunk | beber |
| drive | drives | driving | drove | driven | conducir |
| dwell | dwells | dwelling | dwelled | dwelled | residir |
| eat | eats | eating | ate | eaten | comer |
| fall | falls | falling | fell | fallen | caer |
| feed | feeds | feeding | fed | fed | alimentar |
| feel | feels | feeling | felt | felt | sentir |
| fight | fights | fighting | fought | fought | pelear |
| find | finds | finding | found | found | encontrar |
| flee | flees | fleeing | fled | fled | huir |
| fling | flings | flinging | flung | flung | arrojar |
| fly | flies | flying | flew | flown | volar |
| forbid | forbids | forbidding | forbade | forbidden | prohibir |
| forecast | forecasts | forecasting | forecast | forecast | pronosticar |
| forget | forgets | forgetting | forgot | forgotten | olvidar |
| forgive | forgives | forgiving | forgave | forgiven | perdonar |
| forsake | forsakes | forsaking | forsook | forsaken | abandonar |
| freeze | freezes | freezing | froze | frozen | congelar |
| get | gets | getting | got | gotten | obtener |
| give | gives | giving | gave | given | dar |
| go | goes | going | went | gone | ir |
| grind | grinds | grinding | ground | ground | moler |
| grow | grows | growing | grew | grown | crecer |
| handwrite | handwrites | handwriting | handwrote | handwritten | escribir a mano |
| hang | hangs | hanging | hung | hung | colgar |
| have | has | having | had | had | tener |
| hear | hears | hearing | heard | heard | oír |
| hide | hides | hiding | hid | hidden | esconder |
| hit | hits | hitting | hit | hit | golpear |
| hold | holds | holding | held | held | sostener |
| hurt | hurts | hurting | hurt | hurt | herir |
| inlay | inlays | inlaying | inlaid | inlaid | incrustar |
| input | inputs | inputting | input | input | ingresar |
| inset | insets | insetting | inset | inset | insertar |
| interweave | interweaves | interweaving | interwove | interwoven | entrelazar |
| keep | keeps | keeping | kept | kept | mantener |
| kneel | kneels | kneeling | knelt | knelt | arrodillarse |
| knit | knits | knitting | knitted | knitted | tejer |
| know | knows | knowing | knew | known | saber |
| lay | lays | laying | laid | laid | colocar |
| lead | leads | leading | led | led | liderar |
| lean | leans | leaning | leaned | leaned | inclinarse |
| leap | leaps | leaping | leaped | leaped | saltar |
| learn | learns | learning | learned | learned | aprender |
| leave | leaves | leaving | left | left | dejar |
| lend | lends | lending | lent | lent | prestar |
| let | lets | letting | let | let | permitir |
| lie | lies | lying | lay | lain | yacer |
| light | lights | lighting | lighted | lighted | iluminar |
| lose | loses | losing | lost | lost | perder |
| make | makes | making | made | made | hacer |
| mean | means | meaning | meant | meant | significar |
| meet | meets | meeting | met | met | conocer |
| mislead | misleads | misleading | misled | misled | engañar |
| mistake | mistakes | mistaking | mistook | mistaken | equivocar |
| mow | mows | mowing | mowed | mowed | segar |
| outbid | outbids | outbidding | outbid | outbid | superar una oferta |
| outdo | outdoes | outdoing | outdid | outdone | superar |
| outgrow | outgrows | outgrowing | outgrew | outgrown | superar en crecimiento |
| output | outputs | outputting | output | output | producir |
| outrun | outruns | outrunning | outran | outrun | correr más rápido |
| outsell | outsells | outselling | outsold | outsold | vender más |
| overdo | overdoes | overdoing | overdid | overdone | exagerar |
| overdraw | overdraws | overdrawing | overdrew | overdrawn | sobregirar |
| overeat | overeats | overeating | overate | overeaten | comer en exceso |
| overfly | overflies | overflying | overflew | overflown | sobrevolar |
| override | overrides | overriding | overrode | overridden | anular |
| overrun | overruns | overrunning | overran | overrun | invadir |
| oversee | oversees | overseeing | oversaw | overseen | supervisar |
| overshoot | overshoots | overshooting | overshot | overshot | pasarse |
| oversleep | oversleeps | oversleeping | overslept | overslept | dormir de más |
| overtake | overtakes | overtaking | overtook | overtaken | adelantar |
| overthrow | overthrows | overthrowing | overthrew | overthrown | derrocar |
| pay | pays | paying | paid | paid | pagar |
| plead | pleads | pleading | pleaded | pleaded | suplicar |
| prove | proves | proving | proved | proven | probar |
| put | puts | putting | put | put | poner |
| quit | quits | quitting | quit | quit | renunciar |
| read | reads | reading | read | read | leer |
| rebuild | rebuilds | rebuilding | rebuilt | rebuilt | reconstruir |
| redo | redoes | redoing | redid | redone | rehacer |
| remake | remakes | remaking | remade | remade | rehacer |
| rerun | reruns | rerunning | reran | rerun | repetir |
| rewrite | rewrites | rewriting | rewrote | rewritten | reescribir |
| rid | rids | ridding | rid | rid | librar |
| ride | rides | riding | rode | ridden | montar |
| ring | rings | ringing | rang | rung | sonar |
| rise | rises | rising | rose | risen | levantarse |
| run | runs | running | ran | run | correr |
| saw | saws | sawing | sawed | sawn | serrar |
| say | says | saying | said | said | decir |
| see | sees | seeing | saw | seen | ver |
| seek | seeks | seeking | sought | sought | buscar |
| sell | sells | selling | sold | sold | vender |
| send | sends | sending | sent | sent | enviar |
| set | sets | setting | set | set | poner |
| sew | sews | sewing | sewed | sewn | coser |
| shake | shakes | shaking | shook | shaken | agitar |
| shear | shears | shearing | sheared | shorn | esquilar |
| shed | sheds | shedding | shed | shed | derramar |
| shine | shines | shining | shone | shone | brillar |
| shoe | shoes | shoeing | shod | shod | herrar |
| shoot | shoots | shooting | shot | shot | disparar |
| show | shows | showing | showed | shown | mostrar |
| shrink | shrinks | shrinking | shrank | shrunk | encoger |
| shut | shuts | shutting | shut | shut | cerrar |
| sing | sings | singing | sang | sung | cantar |
| sink | sinks | sinking | sank | sunk | hundir |
| sit | sits | sitting | sat | sat | sentarse |
| slay | slays | slaying | slew | slain | matar |
| sleep | sleeps | sleeping | slept | slept | dormir |
| slide | slides | sliding | slid | slid | deslizar |
| sling | slings | slinging | slung | slung | colgar |
| slit | slits | slitting | slit | slit | rajar |
| smell | smells | smelling | smelled | smelled | oler |
| sneak | sneaks | sneaking | sneaked | sneaked | escabullirse |
| speak | speaks | speaking | spoke | spoken | hablar |
| speed | speeds | speeding | sped | sped | acelerar |
| spell | spells | spelling | spelled | spelled | deletrear |
| spend | spends | spending | spent | spent | gastar |
| spill | spills | spilling | spilled | spilled | derramar |
| spin | spins | spinning | spun | spun | girar |
| spit | spits | spitting | spat | spat | escupir |
| split | splits | splitting | split | split | dividir |
| spoil | spoils | spoiling | spoiled | spoiled | arruinar |
| spread | spreads | spreading | spread | spread | extender |
| spring | springs | springing | sprang | sprung | saltar |
| stand | stands | standing | stood | stood | estar de pie |
| steal | steals | stealing | stole | stolen | robar |
| stick | sticks | sticking | stuck | stuck | pegar |
| sting | stings | stinging | stung | stung | picar |
| stink | stinks | stinking | stank | stunk | apestar |
| stride | strides | striding | strode | stridden | caminar |
| strike | strikes | striking | struck | struck | golpear |
| string | strings | stringing | strung | strung | encordar |
| strive | strives | striving | strove | striven | esforzarse |
| sublet | sublets | subletting | sublet | sublet | subarrendar |
| swim | swims | swimming | swam | swum | nadar |
| swing | swings | swinging | swung | swung | columpiar |
| take | takes | taking | took | taken | tomar |
| teach | teaches | teaching | taught | taught | enseñar |
| tear | tears | tearing | tore | torn | desgarrar |
| tell | tells | telling | told | told | decir |
| think | thinks | thinking | thought | thought | pensar |
| thrive | thrives | thriving | thrived | thrived | prosperar |
| throw | throws | throwing | threw | thrown | lanzar |
| thrust | thrusts | thrusting | thrust | thrust | empujar |
| tread | treads | treading | trod | trod | pisar |
| unbend | unbends | unbending | unbent | unbent | enderezar |
| undo | undoes | undoing | undid | undone | deshacer |
| unfreeze | unfreezes | unfreezing | unfroze | unfrozen | descongelar |
| uphold | upholds | upholding | upheld | upheld | sostener |
| upset | upsets | upsetting | upset | upset | molestar |
| wake | wakes | waking | woke | woken | despertar |
| wear | wears | wearing | wore | worn | vestir |
| weave | weaves | weaving | wove | woven | tejer |
| weep | weeps | weeping | wept | wept | llorar |
| wet | wets | wetting | wetted | wetted | mojar |
| win | wins | winning | won | won | ganar |
| wind | winds | winding | wound | wound | enrrollar |
| withdraw | withdraws | withdrawing | withdrew | withdrawn | retirar |
| withstand | withstands | withstanding | withstood | withstood | resistir |
| wring | wrings | wringing | wrung | wrung | retorcer |
| write | writes | writing | wrote | written | escribir |
